### PR TITLE
Unemployed Frenchman Vandalizes Famous Painting

### PR DESCRIPTION
**Pull request by patrickmason8**
Couldn't think of a good way to shorten the title, it says it all.

### CODE REVIEW

**Comment by whanley** [comment]
This is certainly a scandalous story. Perhaps you could look at other historical papers (NYT) to see if you could learn more about the incident? What sort of people visited the Louvre? What was the security like?

Check the blog post instructions again to see about writing in markdown using the template.

**Comment by whanley** [comment]
The image file you refer to, le deluge.jpg, is not included in this pull request.

**Comment by patrickmason8** [comment]
It showed up on mine when I sent it, how do I fix this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by patrickmason8** [comment]
I submitted the final copy of the analysis project through a pull request a few days ago and I’ll be submitted the third issue of my week of the Gazette, I’m not sure how to fix the image issue for the blog post but I’ll try to find a way before the end of the day.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by whanley** [comment]
You need to upload the image file to your fork of the blog post repository, then send a pull request.

**Pull request merged**
