### PR TITLE
Blog Post 2 

### PR DESCRIPTION
**Pull request by Hat15**
This is my first draft of the second blog post, let me know if you would like more links to outside articles. Once more students upload their blog posts I was planning on adding some links to theirs.

### CODE REVIEW

**Comment by whanley** [comment]
This file is not written in markdown. I'll correct it this time, but not next time. Use a text editor, not Oxygen, to produce blog posts.

**Comment by Hat15** [comment]
Thank you, but could you tell me what is incorrect? I wrote it in Atom this time.

-Henry Thompson

On Oct 29, 2016, at 1:00 PM, Will Hanley <notifications@github.com<mailto:notifications@github.com>> wrote:

This file is not written in markdown. I'll correct it this time, but not next time. Use a text editor, not Oxygen, to produce blog posts.

##

**Comment by whanley** [comment]
Still has `<p>` tags.

**Comment by Hat15** [comment]
Oh ok, sorry about that, got confused. I thought those were part of markdown.

-Henry Thompson

On Oct 29, 2016, at 1:03 PM, Will Hanley <notifications@github.com<mailto:notifications@github.com>> wrote:

Still has <p> tags.

##

**Pull request merged**
