### PR TITLE
The Cotton Industry

### PR DESCRIPTION
**Pull request by tdm16g**

### CODE REVIEW

**Comment by whanley** [comment]
Good start. I'd like a bit more work connecting the dots. You can presume that most readers of the Gazette were essentially experts in cotton, which was the biggest business in Egypt. Why would they want to know about this news? What might they make of it? And how was 1907 different from previous decades?

There is a great recent book called Empire of Cotton by Sven Beckert. Find a review of this book and give it a read--it will summarize his main points and help you to contextualize this moment.

**Comment by whanley** [comment]
Also, please add a screenshot of your article.

**Comment by whanley** [comment]
Great! How about an image now?

**Comment by tdm16g** [comment]
article part 1
article part 2
article part 3
egyptiancottonfield

**Pull request merged**
